POST http://localhost:8080/categoria/criar
Content-Type: application/json

{
    "id": 5,
    "categoria": "junao homesexual mais lindo"
    
}

###

GET http://localhost:8080/categoria/
Content-Type:  application/json


###

POST   http://localhost:8080/categoria/atualizar/8
Content-Type:  application/json

{
   
    "categoria":"jterterhgerghdf"
}

###

DELETE  http://localhost:8080/categoria/deletar/285
Content-Type:  application/json


###

GET   http://localhost:8080/categoria/8
Content-Type:  application/json


