-- MySQL Script generated by MySQL Workbench
-- Thu Aug 17 22:17:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema safisa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema safisa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `safisa` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `safisa` ;

-- -----------------------------------------------------
-- Table `safisa`.`imposto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`imposto` (
  `id` INT NOT NULL,
  `uf` VARCHAR(45) NULL,
  `icms` FLOAT NULL,
  `ipi` FLOAT NULL,
  `difal` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`consumivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`consumivel` (
  `id` INT NOT NULL,
  `cod` VARCHAR(45) NULL,
  `descricao` VARCHAR(100) NULL,
  `categoria_id` INT NOT NULL,
  `imposto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consumivel_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_consumivel_imposto1_idx` (`imposto_id` ASC) VISIBLE,
  CONSTRAINT `fk_consumivel_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `safisa`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumivel_imposto1`
    FOREIGN KEY (`imposto_id`)
    REFERENCES `safisa`.`imposto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`categoria` (
  `id` INT NOT NULL,
  `categoria` VARCHAR(45) NULL,
  `consumivel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categoria_consumivel1_idx` (`consumivel_id` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_consumivel1`
    FOREIGN KEY (`consumivel_id`)
    REFERENCES `safisa`.`consumivel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`custo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`custo` (
  `id` INT NOT NULL,
  `hmaquina` FLOAT NULL,
  `zincagem` FLOAT NULL,
  `retifica` FLOAT NULL,
  `tempera` FLOAT NULL,
  `dobra` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`materiaprima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`materiaprima` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `material` VARCHAR(45) NULL,
  `liga` VARCHAR(45) NULL,
  `kgmt` FLOAT NULL,
  `valorkg` VARCHAR(45) NULL,
  `imposto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_materiaprima_imposto1_idx` (`imposto_id` ASC) VISIBLE,
  CONSTRAINT `fk_materiaprima_imposto1`
    FOREIGN KEY (`imposto_id`)
    REFERENCES `safisa`.`imposto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`peca` (
  `id` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `descricao` VARCHAR(100) NULL,
  `massa` FLOAT NULL,
  `consumomes` INT NULL,
  `urlfoto` VARCHAR(100) NULL,
  `urldesenho` VARCHAR(100) NULL,
  `urlsetupdemaquina` VARCHAR(100) NULL,
  `descricaotecnica` VARCHAR(100) NULL,
  `categoria_id` INT NOT NULL,
  `imposto_id` INT NOT NULL,
  `custo_id` INT NOT NULL,
  `materiaprima_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_peca_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_peca_imposto1_idx` (`imposto_id` ASC) VISIBLE,
  INDEX `fk_peca_custo1_idx` (`custo_id` ASC) VISIBLE,
  INDEX `fk_peca_materiaprima1_idx` (`materiaprima_id` ASC) VISIBLE,
  CONSTRAINT `fk_peca_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `safisa`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peca_imposto1`
    FOREIGN KEY (`imposto_id`)
    REFERENCES `safisa`.`imposto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peca_custo1`
    FOREIGN KEY (`custo_id`)
    REFERENCES `safisa`.`custo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peca_materiaprima1`
    FOREIGN KEY (`materiaprima_id`)
    REFERENCES `safisa`.`materiaprima` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`fornecedor` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  `contato` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`fornecedor_has_consumivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`fornecedor_has_consumivel` (
  `fornecedor_id` INT NOT NULL,
  `consumivel_id` INT NOT NULL,
  PRIMARY KEY (`fornecedor_id`, `consumivel_id`),
  INDEX `fk_fornecedor_has_consumivel_consumivel1_idx` (`consumivel_id` ASC) VISIBLE,
  INDEX `fk_fornecedor_has_consumivel_fornecedor1_idx` (`fornecedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedor_has_consumivel_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `safisa`.`fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_has_consumivel_consumivel1`
    FOREIGN KEY (`consumivel_id`)
    REFERENCES `safisa`.`consumivel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`peca_has_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`peca_has_fornecedor` (
  `peca_id` INT NOT NULL,
  `fornecedor_id` INT NOT NULL,
  PRIMARY KEY (`peca_id`, `fornecedor_id`),
  INDEX `fk_peca_has_fornecedor_fornecedor1_idx` (`fornecedor_id` ASC) VISIBLE,
  INDEX `fk_peca_has_fornecedor_peca1_idx` (`peca_id` ASC) VISIBLE,
  CONSTRAINT `fk_peca_has_fornecedor_peca1`
    FOREIGN KEY (`peca_id`)
    REFERENCES `safisa`.`peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peca_has_fornecedor_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `safisa`.`fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`prestadordeservico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`prestadordeservico` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  `contato` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`peca_has_prestadordeservico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`peca_has_prestadordeservico` (
  `peca_id` INT NOT NULL,
  `prestadordeservico_id` INT NOT NULL,
  PRIMARY KEY (`peca_id`, `prestadordeservico_id`),
  INDEX `fk_peca_has_prestadordeservico_prestadordeservico1_idx` (`prestadordeservico_id` ASC) VISIBLE,
  INDEX `fk_peca_has_prestadordeservico_peca1_idx` (`peca_id` ASC) VISIBLE,
  CONSTRAINT `fk_peca_has_prestadordeservico_peca1`
    FOREIGN KEY (`peca_id`)
    REFERENCES `safisa`.`peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peca_has_prestadordeservico_prestadordeservico1`
    FOREIGN KEY (`prestadordeservico_id`)
    REFERENCES `safisa`.`prestadordeservico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`submontagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`submontagem` (
  `id` INT NOT NULL,
  `cod` VARCHAR(45) NULL,
  `descriçao` VARCHAR(45) NULL,
  `urlfoto` VARCHAR(100) NULL,
  `peca_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_submontagem_peca1_idx` (`peca_id` ASC) VISIBLE,
  CONSTRAINT `fk_submontagem_peca1`
    FOREIGN KEY (`peca_id`)
    REFERENCES `safisa`.`peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`estoque` (
  `peca_id` INT NOT NULL,
  `consumivel_id` INT NOT NULL,
  INDEX `fk_estoque_peca1_idx` (`peca_id` ASC) VISIBLE,
  INDEX `fk_estoque_consumivel1_idx` (`consumivel_id` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_peca1`
    FOREIGN KEY (`peca_id`)
    REFERENCES `safisa`.`peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_consumivel1`
    FOREIGN KEY (`consumivel_id`)
    REFERENCES `safisa`.`consumivel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`estoqueservo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`estoqueservo` (
  `submontagem_id` INT NOT NULL,
  INDEX `fk_estoqueservo_submontagem1_idx` (`submontagem_id` ASC) VISIBLE,
  CONSTRAINT `fk_estoqueservo_submontagem1`
    FOREIGN KEY (`submontagem_id`)
    REFERENCES `safisa`.`submontagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`pedido` (
  `id` INT NOT NULL,
  `numerodepedido` INT NULL,
  `cliente` VARCHAR(45) NULL,
  `ciadde` VARCHAR(45) NULL,
  `submontagem_id` INT NOT NULL,
  `peca_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_submontagem1_idx` (`submontagem_id` ASC) VISIBLE,
  INDEX `fk_pedido_peca1_idx` (`peca_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_submontagem1`
    FOREIGN KEY (`submontagem_id`)
    REFERENCES `safisa`.`submontagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_peca1`
    FOREIGN KEY (`peca_id`)
    REFERENCES `safisa`.`peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`estoquemp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`estoquemp` (
  `materiaprima_id` INT NOT NULL,
  INDEX `fk_estoquemp_materiaprima1_idx` (`materiaprima_id` ASC) VISIBLE,
  CONSTRAINT `fk_estoquemp_materiaprima1`
    FOREIGN KEY (`materiaprima_id`)
    REFERENCES `safisa`.`materiaprima` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safisa`.`emprodução`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safisa`.`emprodução` (
  `id` INT NOT NULL,
  `tempomaquina` VARCHAR(45) NULL,
  `peca_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_emprodução_peca1_idx` (`peca_id` ASC) VISIBLE,
  CONSTRAINT `fk_emprodução_peca1`
    FOREIGN KEY (`peca_id`)
    REFERENCES `safisa`.`peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
